### ISSUE TITLE
Doesn't work on reboot

### ISSUE THREAD

**Issue by Chr0nicYT** [MycroftAI/enclosure-picroft#1]
Hello!
I instars picroft, and ot listened well, that is, until it restarted. The picroft then didn't hear my microphone at all. Any help?
Thanks!

**Comment by Ertain** [comment]
My PiCroft can't hear my microphone, either.  I've tried the microphone test, and AFAIK, the microphone works.

**Ninja Edit**: I've tried giving MyCroft some commands, but it can't understand me.  When I run it, the program apparently can't get a secure connection to `api.mycroft.ai`.

**Comment by kfezer** [comment]
Are you still having this issue with the newest build?

**Comment by Ertain** [comment]
Sorry, haven't used it in weeks.  But I think I was able to get it to work with newer builds.

**Comment by kfezer** [comment]
Cool, just wanted to see if I could close this issue. We can make a new issue later if it happens for you again
