### ISSUE TITLE
Unable to re-enter setup-wizard

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/enclosure-picroft#113]
After completing an initial set up of Picroft, the `mycroft-setup-wizard` command is intended to re-run the setup-wizard. This successfully runs however does not prompt for any changes as the script detects that selections have already been set. Instead the command simply checks for updates and then launches the CLI.

My understanding is that the command should allow a complete re-run of the setup-wizard enabling users to select new input/output devices etc.

I'm assuming a recent update to the setup script is preventing a proper re-run of the wizard.

**Comment by rajdpandey** [comment]
so is this issue solved yet or still open?

**Comment by krisgesling** [comment]
I haven't had time to look at it, so assuming it's still an issue. Have added a help wanted flag to see if anyone in the broader Community is interested in taking a look.

**Comment by penrods** [comment]
I believe this is solved in the Buster image.  I have it wipe out the options file:  https://github.com/MycroftAI/enclosure-picroft/blob/buster/home/pi/auto_run.sh#L726

**Comment by krisgesling** [comment]
Yeah, can confirm that, I re-entered setup a few days ago. Closing.
