### ISSUE TITLE
auto_run.sh use of Ping of 1.1.1.1 doesn't work

### ISSUE THREAD

**Issue by JimPos** [MycroftAI/enclosure-picroft#126]
auto_run.sh appears to use a ping of 1.1.1.1 to test for network connection.
This does not work for me, resulting in picroft saying there is no network connection.
Ping of active ip addresses (e.g., google.com) works fine.

**Comment by penrods** [comment]
So you can't run 'ping 1.1.1.1' from the command either?  Do you mind me asking where you are located or if you have an unusual network setup?  Also, does 'ping 8.8.8.8' work for you?  If so, perhaps we could add a backup test.

**Comment by JimPos** [comment]
Sorry, my mistake.
My router was blocking pings using direct ip address.
Somehow it was accepting pings using site names.
