### ISSUE TITLE
About Image File 

### ISSUE THREAD

**Issue by Anujraval24** [MycroftAI/enclosure-picroft#14]
Pi Croft Image File Is Corrupted , can't make Bootable Sd card

**Comment by kfezer** [comment]
Can you share the link you're using?

How are you trying to make the SD card: what OS, what program?

**Comment by Anujraval24** [comment]
The image of picroft Bootable now but the new issue is this.. can you help
me with these?
Please find attachment.
What should i do after this ?
can't see the wifi named SSID of "MYCROFT" so what's the fix?
Should i need to buy a new wifi module for that?

**Comment by kfezer** [comment]
Ok, glad to here that works. 

You should be able to add the wifi manually through these steps:
https://github.com/MycroftAI/enclosure-picroft/wiki/HOWTO-Manually-Configure-WiFi
