### ISSUE TITLE
Make use of GitHub Releases vs Google Drive for images

### ISSUE THREAD

**Issue by prasket** [MycroftAI/enclosure-picroft#157]
Currently the pi images that are offered pre-built are hosted on Google Drive. 

I propose the project quit using Google Drive for these images and embrace using Github releases for hosting the within the repo. https://github.com/MycroftAI/enclosure-picroft/releases 

Having the image stored in Google goes against the privacy mindset of the project as many know Google is one of the most privacy violating companies in the world.

**Comment by krisgesling** [comment]
Hey Prasket, 

There's a size limit on the Github releases that Picroft far exceeds. However you can find all the Picroft releases here: 
https://downloads.mycroft.ai/releases/picroft/

We had a brief outage a little while ago and I switched the download links to GDrive while we were investigating but clearly didn't  point them back. This has been fixed up now.

Thanks for the nudge :)

**Comment by prasket** [comment]
Ahh makes sense, Thank you for update @krisgesling
