### ISSUE TITLE
how to change the wake word in picroft

### ISSUE THREAD

**Issue by raja434** [MycroftAI/enclosure-picroft#22]
hi how can i change the wake word in picroft

**Comment by forslund** [comment]
Hi, to change wake word go to https://home.mycroft.ai and then to settings -> advanced
and enter the wakeword and corresponding phonemes under _Listener_*.

Phonemes for words can be looked up using http://www.speech.cs.cmu.edu/cgi-bin/cmudict

After this changes has been made, restart your picroft unit.

**Comment by penrods** [comment]
Answered, closing.

**Comment by kmccurley** [comment]
I believe that this answer only applies to the older PocketSphinx system, but not precise?

**Comment by penrods** [comment]
Precise will only be used if there is a model for the given wakeword.  Currently the only published model is "Hey Mycroft" (although you can build your own if you want to try that).

When there is no model for the wakeword, mycroft-core will fall back to using PocketSphinx.
