### ISSUE TITLE
amixer command sets Master Volume, not output source

### ISSUE THREAD

**Issue by t0ddpar0dy** [MycroftAI/enclosure-picroft#26]
After some troubleshooting of my own I discovered that `amixer cset numid=3` is the `scontrol` for `Master Playback Volume.`

Where `auto_run.sh` and `startup_auto_run.sh` state
```
amixer cset numid=3 "1" # audio out the analog speaker/headphone jack 
#amixer cset numid=3 "2" # audio out the HDMI por (e.g. TV speakers)
```
...we are simply setting the `Master Playback Volume` to `1` or `2` but we don't notice that at runtime because the very next command readjusts the volume
```
amixer set Master 75% # set volume to a reasonable level

```

Recommend removing the following lines as they do not change the output source
```
amixer cset numid=3 "1" # audio out the analog speaker/headphone jack 
#amixer cset numid=3 "2" # audio out the HDMI por (e.g. TV speakers)
```
I haven't succeeded in finding the actual commands to switch output sources. Will keep looking

**Comment by penrods** [comment]
I think this no longer applies.  I'm going to close this, but feel free to reopen if there is still an issue.
