### ISSUE TITLE
Add msm install <keyword>

### ISSUE THREAD

**Issue by kfezer** [MycroftAI/enclosure-picroft#3]
Allow install by keyword rather than github http link. Makes it more user accessible. For example:

```
msm install pandora
```
installs the pandora radio skill to picroft

**Comment by penrods** [comment]
To be a little clearer, it would reach out to https://github.com/MycroftAI/mycroft-skills to find the submodule link with a matching name.  Then it will follow that link to get the path to the appropriate .git path.  Install from the "master" branch of the submodule.
