### ISSUE TITLE
Tested on Pi Zero?

### ISSUE THREAD

**Issue by krishnakanthpps** [MycroftAI/enclosure-picroft#32]
Hi. 

Has this been tested on Pi Zero W. Also, if it is connected to a HDMI device which has both display and audio, would it send audio to the HDMI connected device? or I use a sound card would it work?

This is specifically for the Pi Zero W version. 

Or is the processing power of the Pi Zero not good enough for the Picroft to work well?

**Comment by forslund** [comment]
I don't think anyone has tested. The processing power of the Zero looks a bit on the poor side for running Mycroft in a good way at least at the moment.

**Comment by penrods** [comment]
You will not be able to run well on a PiZero if at all.  Mycroft requires a Pi3 to run well, even on a Pi2 the experience is very laggy.

**Comment by penrods** [comment]
Closing as an issue.
