### ISSUE TITLE
How to turn off Display Manager

### ISSUE THREAD

**Issue by thekidfromoak** [MycroftAI/enclosure-picroft#33]
To boost performance, is there a configuration param to turn off the Display Manager when no faceplate is being used? I'm running cli and am constantly seeing "setting active skill to..." along with img_codes. I have tried stopping the enclosure service and this does not seem to make a difference. I have my enclosure set as picroft using the remote settings.

**Comment by LearnedVector** [comment]
Currently there is no way to turn off the Display Manager. You can filter out the display manager in the cli using this command

`:filter "Display Manager"`

The filter command takes out the entire output line in the cli.

Feel free to replace Display Manager with any other strings you want to filter out.

**Comment by thekidfromoak** [comment]
Thank you!
