### ISSUE TITLE
subscription voice doesn't work on picroft

### ISSUE THREAD

**Issue by forslund** [MycroftAI/enclosure-picroft#49]
The `/etc/mycroft/mycroft.conf` config overrides tts/voice from the web which will block the unit from using the subscriber voice.

To reproduce the issue:
- select the subscriber voice on home.mycroft.ai
- update the config (hey mycroft, update the configuration)
- allow the voice to be downloaded

The voice should not change to the subscriber voice

Remove the `"voice": "ap"` line from `/etc/mycroft/mycroft.conf` and reboot, the device should now be using the subscriber voice.

**Comment by penrods** [comment]
Fixed in #51
