### ISSUE TITLE
Can't connect to WS Client 

### ISSUE THREAD

**Issue by mustafaxfe** [MycroftAI/enclosure-picroft#52]
Hi,
I have been trying to make Mycroft to work on Raspberry Pi.
I have installed Ubuntu Mate for Raspberry Pi 3 and also I followed this tutorial "https://github.com/MycroftAI/enclosure-picroft/wiki/Script-for-building-Picroft-image". While installation there was no error. But I couldn't make it work.
It gives this error at every new new terminal:

> 14:46:05.609 - mycroft.messagebus.client.ws:on_error:71 - ERROR - Exception("Uncaught 'error' event.",)
>                          14:46:05.622 - mycroft.messagebus.client.ws:on_error:72 - WARNING - WS Client will reconnect in 60 seconds.

Also it gives these errors:

14:39:47.374 - mycroft.configuration.config:load_local:128 - DEBUG - Configuration /usr/local/lib/python2.7/site-packages/mycroft_core-0.9.17-py2.7.egg/mycroft/configuration/mycroft.conf loaded
14:39:47.387 - mycroft.configuration.config:load_local:128 - DEBUG - Configuration /usr/local/lib/python2.7/site-packages/mycroft_core-0.9.17-py2.7.egg/mycroft/configuration/mycroft.conf loaded
14:39:47.397 - mycroft.configuration.config:load_local:128 - DEBUG - Configuration /etc/mycroft/mycroft.conf loaded
14:39:47.402 - mycroft.configuration.config:load_local:133 - DEBUG - Configuration '/home/connecticals/.mycroft/mycroft.conf' not found
14:39:47.434 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
14:39:48.628 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device//setting HTTP/1.1" 401 38
14:39:48.645 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
14:39:49.975 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/auth/token HTTP/1.1" 401 38
**14:39:50.001 - mycroft.configuration.config:__init__:175 - ERROR - HTTPError fetching remote configuration: 401**
14:39:50.011 - mycroft.configuration.config:load_local:133 - DEBUG - Configuration '/opt/mycroft/web_config_cache.json' not found
14:39:50.022 - mycroft.configuration.config:load_local:128 - DEBUG - Configuration /etc/mycroft/mycroft.conf loaded
14:39:50.032 - mycroft.configuration.config:load_local:133 - DEBUG - Configuration '/home/connecticals/.mycroft/mycroft.conf' not found

I have installed Mycroft on Miniconda with these addinational steps:

conda create -n mycroft pip python=2.7

And also I have added these lines to "auto_run.sh"

export PATH="/home/connecticals/miniconda/bin:$PATH"
source activate mycroft

* My hardware is Raspberry Pi 3
* My OS is Ubuntu Mate ( 16.04 )
* With version 0.9.17 of the Mycroft software
* With the standard Wake Word

Also I saw a package that is mycroft-picroft. Should I have to install it?

Thanks in advance.

**Comment by penrods** [comment]
"Picroft" is specifically Raspbian + Mycroft.  If you are attempting to do anything else you should do what we call a Github install of the https://github.com/mycroftai/mycroft-core repo itself and do whatever you need to do to get your system configured.  It should work, as we run under Ubuntu and Raspbian is also a Debian-based OS.  But you are kinda on your own -- we can't directly support every variation of OS and hardware!
