### ISSUE TITLE
Could not request Speech Recognition recognition request failed: Not Authorized

### ISSUE THREAD

**Issue by MyNameIsJulian** [MycroftAI/enclosure-picroft#53]
Picroft on Raspberry Pi 3 Model B.
Connection: Ethernet
Version: 0.9.17
Image written: Using the following command on Linux; sudo dd if=imagename.img of=device oflag=sync bs=4M
Microphone: PS3 Eyecam

The issue I'm having is that Mycroft works, except for voice recognition. Saying "Hey Mycroft" works fine and I get the activation sound, but then it just stays silent and outputs the following.
`mycroft.client.speech.listener:transcribe:168 - ERROR - Could not request Speech Recognition recognition request failed: Not Authorized`

**Comment by nogueira** [comment]
same here

**Comment by penrods** [comment]
@Julian2000nl and @nogueira -- Can you try the https://mycroft.ai/to/picroft-unstable build (2018-03-14)?  I believe it should clear up several issues, including what you describe here.
