### ISSUE TITLE
Raspberry pi 3 B+ not working with the latest image realeased

### ISSUE THREAD

**Issue by zhampu** [MycroftAI/enclosure-picroft#57]
The latest image it not working on my raspberry pi 3 B+ but it works with my Raspberry pi 3 B.

Any advices on how to make it work?

**Comment by prasket** [comment]
Came here wondering the same thing. Raspbian by itself works fine, raspbian_Picroft_2018-03-14 does not on my pi 3 B+. Just got the pi last night. 

Also found this 

> Note that when using an RPI 3B+ a lightening bolt icon can be produced by older software that misinterpreted the (probably) changed register structures of an PI 3B+, so a lightening icon can mean that you are using incompatible (boot) software with a 3B+.

from: [https://www.raspberrypi.org/forums/viewtopic.php?p=1296853](https://www.raspberrypi.org/forums/viewtopic.php?p=1296853)

My work-around is going to try and install mycroft-core on Raspbian myself. [https://github.com/MycroftAI/mycroft-core/blob/dev/README.md](https://github.com/MycroftAI/mycroft-core/blob/dev/README.md)

**Comment by prasket** [comment]
Just came across this from the docs.. this issues should be closed out. 

> Raspberry Pi compatibility chart
    Pi3 B+ : COMING SOON <– Not currently supported

https://mycroft.ai/documentation/picroft/#raspberry-pi-compatibility-chart

**Comment by KathyReid** [comment]
Hi @prasket thanks for your feedback. Until we have a working Picroft image that works out of the box on a 3B+, we need to leave the "coming soon" in the docs so people don't get frustrated when they try to install it on a 3B+ and it doesn't work. 

We're in discussions internally around whether we need two separate images - one for Raspbian for pre-3B+ hardware, and one for Stretch for 3B+ and later hardware. What are your thoughts on that?

Best, Kathy

**Comment by a2sphinx** [comment]
Same thing I've got when trying to install it in my new 3B+ only lightning symbol and rainbow is showing. Hope this issue will resolve as soon as possible to try Picroft. Waiting for the good news whatever the finalized solution is.

**Comment by dannystaple** [comment]
Hi @KathyReid why two separate images? Is that due to backwards compatibility issues with older Pi's.

**Comment by penrods** [comment]
We weren't certain if we could support both the Pi3 and the Pi3B+ on the same image.  The Pi3B+ MUST run on Raspbian Stretch, and the current image is using Jessie Lite.  I'm getting closer to a solution, but there are a few challenges -- the Pi3B+ changed the wifi chipset, so the current captive-portal solution isn't working, you have to enter wifi connection info using a keyboard/monitor.

You can preview this at https://mycroft.ai/to/picroft-unstable.  This is generally working but will likely change in some substantial ways, so avoid it unless you are willing to re-download a 2.3GB image a second or third time in the next few weeks.

**Comment by kgleason** [comment]
This seems to have petered out a bit. Any new updates on Pi3B+ support?

**Comment by forslund** [comment]
@kgleason the latest picroft image should work on the Pi3B+

**Comment by kgleason** [comment]
Sweet. I wasn't sure since this issue is still open, and the page still says unsupported (or it did yesterday).

Thanks for letting me know!

**Comment by forslund** [comment]
Which page exactly?

**Comment by kgleason** [comment]
https://mycroft.ai/documentation/picroft/#raspberry-pi-compatibility-chart

![picroft_support](https://user-images.githubusercontent.com/2130628/47730546-c8350f80-dc38-11e8-9327-64359f2140ea.png)

**Comment by forslund** [comment]
Thanks, that should be updated.

**Comment by kgleason** [comment]
@forslund is the latest image that you reference from Sept 12, 2018? If so, it seems to have some issues still.

**Comment by penrods** [comment]
Can you be more specific than "some issues"?  Do you mean it won't run on a Pi3 B+?  I know I've launched it there successfully.

The image is https://mycroft.ai/to/picroft-image (which does redirect to the 2018-9-12 version).

**Comment by forslund** [comment]
@kgleason like @penrods I've been running it for quite some time now without major issues. It's used in the mycroft-core release verification process as well.

**Comment by elik745i** [comment]
Hey there, installed unstable release on PI3B+, looks like I've setup wifi, but picroft still can't connect and asking me questions at every boot, the starts and I can update raspbian over sudo apt-get update and upgrade, but when asking questions? picroft recognizes speach and replies that it can not connect to the services... (((

**Comment by krisgesling** [comment]
Hi all, this seems like a resolved issue as our Picroft images are now based on Stretch, so I'm going to close it out.

@elik745i, sorry we didn't see your message, hoping you got that wifi sorted out. If you're still having trouble please jump over to [our Forums](https://community.mycroft.ai) and we can help you get up and running.
