### ISSUE TITLE
aplay issue change for Wav

### ISSUE THREAD

**Issue by kfezer** [MycroftAI/enclosure-picroft#7]
Fix aplay so it stops freezing after a few plays.

**Comment by penrods** [comment]
Fixed.

When you initiate the playing of a WAV file via the default, it was sometimes locking up for 30 seconds. The problem appears to actually be between ALSA/PulseAudio on a Raspberry Pi. From online comments, I believe this is a known issue that gets made worse on the Raspberry Pi, which generates analog audio using the CPU/interrupts. This is not a problem when using HDMI (digital) audio.

To work around this issue, we can use a command line that explicitly bypasses PulseAudio and plays to the ALSA hardware device. The ability to specify the "play_wav_cmdline" was added to mycroft-core, and we added a configuration for Picroft to use this capability.
