### ISSUE TITLE
Picroft2: pulseaudio or not...

### ISSUE THREAD

**Issue by andlo** [MycroftAI/enclosure-picroft#73]
I have installed new image, and got google AIY working.

But if installing pulseaudio mycroft cant set volume. If not having installed pulseaudio he can set volume.

Cant figure out why and how to fix.

I think I need pulse audio to get mix on google AIY working whith mycroft. It works whitout pulseaudio outside mycroft - and whith mycroft-mic-test but non when mycrofr is running (gues the voice part dosnt really work vhitout pulse)

**Comment by forslund** [comment]
A couple of questions around this:

If you open the mycroft cli does the mic input show there? I'm wondering if it's only an issue with audio output? 

Does wakewords trigger the listening sound

The default play_wav commands use paplay and may need to be changed to aplay (maybe this is already done on the picroft image)

**Comment by andlo** [comment]
The mic does show there also if not using pulse - it starts by changing level and stops. 

Where can I check default play_wav ? 

I did change in mycroft.conf line for aplay and mpg123 to get YIY voicehat working, but that is regarding sound. The problem is mic is hanging when not using pulse.

**Comment by forslund** [comment]
If it's changed from the default there should be an entry in the `/etc/mycroft/mycroft.conf` file. or `~/.mycroft/mycroft.conf`

**Comment by andlo** [comment]
OK - so picroft is not supposed to use pulseaudio? I just cant get him to function whitout :( problems whit mic is hanging. 
Testing mic whith arecord and aplay is working altså whitout pulse.

**Comment by forslund** [comment]
:( I don't believe we've done any tests without PulseAudio but the the technology stack doesn't depend on it. speechrecognition uses PythonAudio which is a wrapper around portaudio which in turn should work on bare alsa.

But as previously stated our reference systems all run with pulseaudio.

Is the only issue when running pulseaudio that the volume skill doesn't function?

**Comment by andlo** [comment]
Yes the only issue using pulseaudio is volume skill dosnt function - or it does, and it changes volume which can be seen by alsamixer, but sound output is not afected.
read somewhere that there is a issue (or were in earlier dayes) whit volumelevel and raspbian when using pulseaudio :( 

Strange thing is mic and volume did work fine on picroft v.1 image (the one based on jessie) 

The new picroft image dosnt have pulseaudio installed by default - I dont know if the old one did.
Maybe pulseaudio should be in the new image by default  ?

**Comment by penrods** [comment]
#85 deals with this, closing
