### ISSUE TITLE
Picroft2: update system as first thing after booting new install up

### ISSUE THREAD

**Issue by andlo** [MycroftAI/enclosure-picroft#74]
When setting up Picroft as the auto_run.sh should be dooing a systemupdate as the first thing

sudo apt-get update
sudo apt-get upgrade
sudo reboot 

And maybe inform the user that it is updating….

Reason is that I see that mycroft dosnt come up right if not done - it fails starting some of the servises.

**Comment by penrods** [comment]
The new unstable image should address this issue.
