### ISSUE TITLE
Discrepancies in build instructions

### ISSUE THREAD

**Issue by mhaddy** [MycroftAI/enclosure-picroft#75]
There are several minor discrepancies in the instructions for the custom build images. Here are the two versions of documentation I'm comparing:

1. https://mycroft.ai/documentation/picroft/picroft-image/
2. https://github.com/MycroftAI/enclosure-picroft/blob/stretch/image_recipe.md

These should be merged or updated to be in-sync to avoid confusion. Examples of discrepancies:

1 instructs the user to:
--> 'B2 Console Autologin'
--> 'I3 Change Keyboard Layout'
--> 'Generic 101-key PC'
- '7 Advanced Options'
-->'A1 Expand Filesystem'

while 2 does not have these doesn't have the majority of these instructions and also instructs the user to select Pick Generic 104-key PC.

And then from here on out, the two documents are drastically different. 1 appears to be more outdated asking the user to install mycroft repos, git, vim, cron jobs, platform detection scripts and more while 2 just asks you to do the following:

cd ~
wget -N https://rawgit.com/MycroftAI/enclosure-picroft/stretch/home/pi/update.sh
bash update.sh

As this is my first go at building the Picroft, I'm following 2 and are in the midst of running the bash update script. I'll update this issue with the results of my test.

**Comment by penrods** [comment]
I agree, the "recipe" is the definitive version.  @KathyReid, fixed it so that the documentation page now points to the recipe which lives in Github.

Thanks for pointing this out!
