### ISSUE TITLE
Creating a raspbian full build for development purposes

### ISSUE THREAD

**Issue by congruentsquare** [MycroftAI/enclosure-picroft#82]
I am running into a bunch of issues with the installation script due to different configs(or something else). Many people need a gui for development purposes and was wondering if there could be a full raspbian(non-lite) image release with picroft? It would greatly simplify mycroft development on the pi.

**Comment by penrods** [comment]
Running the full Raspbian GUI really doesn't work well.  You are asking too much of the processor to run the voice assistant and the GUI.  If someone wants to take the time to try it again and see if it is usable, I'll look into it.  But the last time I tried it just wasn't useful.

**Comment by andlo** [comment]
I am nearly finish on a skill that do install a compleate IDE with all the stuff needed to make skills etc. for mycroft. The IDE is installed localy on the device, and can be accesed throu a webbrowser. 

https://github.com/andlo/theia-ide-skill

**Comment by jshep321** [comment]
Hi @penrods ,
Just a suggestion, but I think this (full desktop + picroft) should be a target for the buster image given the horsepower on the pi4.  

Personally, I'm envisioning a custom skill that shows photos/artwork  (chromium browser in kiosk mode) when idle, and mopidy/spotify when active.  

Thoughts?
