### ISSUE TITLE
Version/checksum mismatch in README link

### ISSUE THREAD

**Issue by juhi24** [MycroftAI/enclosure-picroft#94]
The image download link in README.md is labelled "Picroft 2018-9-12 unstable image". However, the link points to a file called `raspbian-stretch_Picroft_2018-12-17.img.zip` in google drive. The SHA256 checksum on the README does not match with the zipped nor the unzipped image. Please either update the description and the checksum, or the link to point to the correct image.

Further, is there a reason why the images are not provided on the releases tab in Github?

**Comment by krisgesling** [comment]
Hi Jussi,

The checksums are now updated, thanks for pointing it out. 

Github have a maximum 2GB file size for release binaries so unfortunately our images don't quite fit :(
