### ISSUE TITLE
Is it possible to install mycroft alongside raspbian stretch lite?

### ISSUE THREAD

**Issue by r1bnc** [MycroftAI/enclosure-picroft#96]
Hi, Can I install mycroft using the procedures in: https://github.com/MycroftAI/mycroft-core/blob/dev/README.md
I do not like to reimage a microSD, I need to install it alongside my Raspbian Lite. Is it possible?

**Comment by penrods** [comment]
Yes, see the "recipe" we followed to create the Picroft image.

https://github.com/MycroftAI/enclosure-picroft/blob/stretch/image_recipe.md
