### ISSUE TITLE
Picroft images are outdated

### ISSUE THREAD

**Issue by pbajno** [MycroftAI/enclosure-picroft#99]
Password for current google drive images is mycroft or raspberry?
Could you update those images? They are almost one year old. That's huge.

**Comment by krisgesling** [comment]
Hi pbajno, the default password is mycroft. 

We are aiming to release a new image for 19.02, we just have a few other priorities at the moment, so need to find some time to dedicate to this.

**Comment by penrods** [comment]
You can try the new unstable image at: https://mycroft.ai/to/picroft-unstable

Once I'm comfortable that it is up to snuff, this will be promoted to stable.  But I'm pretty sure it is solid right now.

**Comment by penrods** [comment]
Both  https://mycroft.ai/to/picroft-unstable and  https://mycroft.ai/to/picroft-image are pointing to the latest and greatest now!  This is a 19.2.13 install, by default, and will auto-upgrade.
